name: langchain-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.5.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.12.0
  - python-dateutil=2.9.0
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - attrs==23.2.0
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - dataclasses-json==0.6.4
      - distro==1.9.0
      - frozenlist==1.4.1
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - idna==3.6
      - jsonpatch==1.33
      - jsonpointer==2.4
      - langchain==0.1.13
      - langchain-community==0.0.29
      - langchain-core==0.1.34
      - langchain-openai==0.1.1
      - langchain-text-splitters==0.0.1
      - langsmith==0.1.33
      - marshmallow==3.21.1
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - openai==1.14.3
      - orjson==3.9.15
      - packaging==23.2
      - pgvector==0.2.5
      - psycopg2-binary==2.9.9
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.29
      - tenacity==8.2.3
      - tiktoken==0.6.0
      - tqdm==4.66.2
      - typing-inspect==0.9.0
      - urllib3==2.2.1
      - yarl==1.9.4
